services:
  - type: web
    name: screenshot-app
    env: node
    plan: free
    buildCommand: |
      # Update package lists and install Chromium
      echo "=== Installing Chromium ==="
      sudo apt-get update
      sudo apt-get install -y chromium chromium-browser
      
      # Create necessary directories with proper permissions
      echo "=== Setting up directories ==="
      sudo mkdir -p /opt/render/chrome
      sudo mkdir -p /opt/render/.cache/puppeteer
      sudo chmod -R 777 /opt/render/.cache/puppeteer
      sudo chmod -R 777 /opt/render/chrome
      
      # Create symlink for Chrome
      echo "=== Creating Chrome symlink ==="
      CHROME_PATH=$(which chromium || which chromium-browser)
      echo "Found Chromium at: $CHROME_PATH"
      sudo ln -sf $CHROME_PATH /opt/render/chrome/chrome
      sudo chmod +x /opt/render/chrome/chrome
      
      # Verify Chrome installation
      echo "=== Verifying Chrome installation ==="
      /opt/render/chrome/chrome --version || echo "Failed to get Chrome version"
      ls -la /opt/render/chrome
      
      # Install dependencies
      echo "=== Installing Node dependencies ==="
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm ci
      
    startCommand: npm start
    healthCheckPath: /
    healthCheckTimeout: 5000
    
    # Environment variables
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /opt/render/chrome/chrome
      - key: CHROME_PATH
        value: /opt/render/chrome/chrome
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
      - key: RENDER
        value: "true"
      - key: PORT
        value: "10000"
      - key: BASE_URL
        value: https://screenshot-app-2.onrender.com

