services:
  - type: web
    name: screenshot-app
    env: node
    plan: free
    buildCommand: |
      # Update package lists and install essential tools
      sudo apt-get update
      sudo apt-get install -y gnupg curl wget ca-certificates

      # Install all Chrome dependencies
      sudo apt-get install -y \
        ca-certificates \
        fonts-liberation \
        libappindicator3-1 \
        libasound2 \
        libatk-bridge2.0-0 \
        libatk1.0-0 \
        libc6 \
        libcairo2 \
        libcups2 \
        libdbus-1-3 \
        libexpat1 \
        libfontconfig1 \
        libgbm1 \
        libgcc1 \
        libglib2.0-0 \
        libgtk-3-0 \
        libnspr4 \
        libnss3 \
        libpango-1.0-0 \
        libpangocairo-1.0-0 \
        libstdc++6 \
        libx11-6 \
        libx11-xcb1 \
        libxcb1 \
        libxcomposite1 \
        libxcursor1 \
        libxdamage1 \
        libxext6 \
        libxfixes3 \
        libxi6 \
        libxrandr2 \
        libxrender1 \
        libxss1 \
        libxtst6 \
        lsb-release \
        xdg-utils \
        libgdk-pixbuf2.0-0 \
        libgtk2.0-0 \
        libnotify-dev \
        libgconf-2-4 \
        libxinerama1 \
        libxkbcommon0 \
        xvfb
      
      # Install Chrome using the recommended method
      echo "===== Installing Chrome ====="
      wget -q -O /tmp/chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      sudo dpkg -i /tmp/chrome.deb || sudo apt-get install -fy
      rm /tmp/chrome.deb
      
      # Verify Chrome installation and show version
      echo "===== Verifying Chrome Installation ====="
      google-chrome-stable --version
      
      # Print Chrome path for debugging
      echo "===== Chrome Path ====="
      which google-chrome-stable
      ls -la /usr/bin/google-chrome-stable
      
      # Create a chrome-user directory and set permissions
      echo "===== Setting up Chrome User Directory ====="
      mkdir -p /tmp/chrome-user-data
      chmod -R 777 /tmp/chrome-user-data
      ls -la /tmp/chrome-user-data
      
      # System checks
      echo "===== System Information ====="
      echo "Memory:"
      free -h
      echo "Disk space:"
      df -h
      echo "CPU info:"
      lscpu | grep "Model name"
      
      # Create test HTML file for Chrome
      echo "===== Creating Test HTML ====="
      cat > /tmp/test.html << EOL
      <!DOCTYPE html>
      <html>
      <head>
        <title>Chrome Test</title>
      </head>
      <body>
        <h1>Chrome Test</h1>
        <p>This is a test page for Chrome.</p>
        <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAYAAACNMs+9AAAAFUlEQVR42mNkYPhfz0AEYBxVSF+FAP4iBBwAlqN0AAAAAElFTkSuQmCC" alt="Test Image">
      </body>
      </html>
      EOL
      
      # Verify Chrome can run headless and capture screenshots
      echo "===== Testing Chrome Headless Mode ====="
      mkdir -p /tmp/chrome-test
      google-chrome-stable --headless --disable-gpu --no-sandbox --disable-dev-shm-usage --user-data-dir=/tmp/chrome-user-data /tmp/test.html --dump-dom
      
      echo "===== Testing Chrome Screenshot Capability ====="
      google-chrome-stable --headless --disable-gpu --no-sandbox --disable-dev-shm-usage --user-data-dir=/tmp/chrome-user-data --screenshot=/tmp/chrome-test/test.png /tmp/test.html
      
      # Verify screenshot was created
      echo "===== Verifying Screenshot Creation ====="
      ls -la /tmp/chrome-test/
      
      # Install Node dependencies with production optimization
      echo "===== Installing Node Dependencies ====="
      npm ci --omit=dev
    startCommand: npm start
    healthCheckPath: /
    healthCheckTimeout: 5000
    
    # Memory and CPU limits
    autoscaling:
      minInstances: 1
      maxInstances: 1
    env: node
    plan: free
    disk:
      name: chrome-data
      mountPath: /tmp/chrome-user-data
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
      # RENDER_EXTERNAL_URL is automatically provided by Render
      - key: RENDER_EXTERNAL_URL
        sync: false
      # Additional Chrome configuration
      - key: CHROME_PATH
        value: /usr/bin/google-chrome-stable
      - key: PUPPETEER_CACHE_DIR
        value: /tmp
      - key: PUPPETEER_DOWNLOAD_HOST
        value: https://storage.googleapis.com

