services:
  - type: web
    name: screenshot-app
    env: node
    plan: free
    buildCommand: |
      # Add Chrome repository and install Chrome
      echo "=== Installing Chrome ==="
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
      sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
      sudo apt-get update
      sudo apt-get install -y google-chrome-stable
      
      # Verify Chrome installation
      echo "=== Verifying Chrome installation ==="
      google-chrome-stable --version
      
      # Create symlink
      sudo ln -sf $(which google-chrome-stable) /usr/bin/chrome
      
      # Install Node dependencies
      echo "=== Installing Node dependencies ==="
      npm ci
      
      # Final verification
      echo "=== Final verification ==="
      /usr/bin/chrome --version
      
    startCommand: npm start
    healthCheckPath: /
    healthCheckTimeout: 5000
    
    # Environment variables
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chrome
      - key: CHROME_PATH
        value: /usr/bin/chrome
      - key: RENDER
        value: "true"
      - key: PORT
        value: "10000"
      - key: BASE_URL
        value: https://screenshot-app-2.onrender.com

